baseURL = "https://yixihan.github.io"
title = "摸鱼小屋"
theme = "gokarna"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true

# Choose one of emacs, trac or perldoc
pygmentsStyle = "monokai"

[params]
  footer = "Hello World"
  avatarURL = "/images/avatar.png"
  AvatarAltText = "avatar"
  avatarSize = "size-m"
  accentColor = "#08F"
  description = "花开亦花散"
  customHeadHTML = '''
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
      });
    </script>
  '''
  showPostsOnHomePage = "popular"
  
  socialIcons = [
    {name = "twitter", url = "https://twitter.com/yixihan2001"},
    # {name = "linkedin", url = "https://example.com"},
    # {name = "stackoverflow", url = "https://example.com"},
    # {name = "dribbble", url = "https://example.com"},
    # {name = "instagram", url = "https://example.com"},
    {name = "email", url = "mailto:3113788997@qq.com"}
  ]
  metaKeywords = ["blog", "gokarna", "hugo"]



[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "面经"
    pre = "<span data-feather='book'></span>"
    url = "/面经/"
    weight = 2

  [[menu.main]]
    name = "Java"
    pre = "<span data-feather='code'></span>"
    url = "/Java/"
    weight = 3

  [[menu.main]]
    name = "MySQL"
    pre = "<span data-feather='code'></span>"
    url = "/MySQL/"
    weight = 4

  [[menu.main]]
    name = "Go"
    pre = "<span data-feather='code'></span>"
    url = "/Go/"
    weight = 5

  [[menu.main]]
    name = "Tags"
    pre = "<span data-feather='tag'></span>"
    url = "/tags/"
    weight = 6

  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/yixihan"
    weight = 7

  [[menu.main]]
    identifier = "buymeacoffee"
    pre = "<span data-feather='coffee'></span>"
    url = "https://www.buymeacoffee.com/avijitgupta"
    weight = 8

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false
